authors/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from . import views

app_name = "authors"
author_api_router = SimpleRouter()
author_api_router.register("api", views.AuthorViewSet, basename="author-api")

urlpatterns = [
    path("register/", views.register_view, name="register"),
    path("register/create/", views.register_create, name="register_create"),
    path("login/", views.login_view, name="login"),
    path("login/create/", views.login_create, name="login_create"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path(
        "dashboard/recipe/create",
        views.DashboardRecipe.as_view(),
        name="dashboard_recipe_create",
    ),
    path(
        "dashboard/recipe/delete/",
        views.DashboardRecipeDelete.as_view(),
        name="dashboard_recipe_delete",
    ),
    path(
        "dashboard/recipe/<int:recipe_id>/edit/",
        views.DashboardRecipe.as_view(),
        name="dashboard_recipe_edit",
    ),
]

urlpatterns += author_api_router.urls

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipes.urls")),
    path("authors/", include("authors.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path, include
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from recipes import views

app_name = "recipes"

recipes_api_v1_router = SimpleRouter()
recipes_api_v1_router.register(
    "recipes/api/v1",
    views.RecipeAPIv1ViewSet,
)

urlpatterns = [
    path("", views.RecipesListViewHome.as_view(), name="home"),
    path("recipes/search/", views.RecipesListSearch.as_view(), name="search"),
    path(
        "recipes/category/<int:category_id>/",
        views.RecipesListCategory.as_view(),
        name="category",
    ),
    path("recipes/<int:pk>/", views.RecipeDetailView.as_view(), name="recipe"),
    path("recipes/api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path(
        "recipes/api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"
    ),
    path("recipes/api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path("", include(recipes_api_v1_router.urls)),
]

recipes/models.py
import string
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db import models
from django.db.models import F, Value
from django.db.models.functions import Concat
from random import choices, SystemRandom


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class RecipeManager(models.Manager):
    def get_published(self):
        return (
            self.filter(is_published=True)
            .annotate(
                author_full_name=Concat(
                    F("author__first_name"),
                    Value(" "),
                    F("author__last_name"),
                    Value(" ("),
                    F("author__username"),
                    Value(
                        ")",
                    ),
                )
            )
            .order_by("-id")
            .select_related("category", "author")
        )


class Recipe(models.Model):
    objects = RecipeManager()
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    # TODO arrumar o nome do field abaixo: prepAration
    preperation_time_unit = models.CharField(max_length=10)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=10)
    preparation_step = models.TextField()
    preparation_step_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to="recipes/covers/%Y/%m/%d/")
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None
    )
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        rand_letters = "".join(
            SystemRandom().choices(string.ascii_letters + string.digits)
        )
        self.slug = slugify(f"{self.title}-{rand_letters}")

        return super().save(*args, **kwargs)

authors/forms/recipe_form.py
from django import forms
from recipes.models import Recipe
from recipes.utils.django_forms import add_attr


class AuthorRecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = Recipe
        fields = (
            "title",
            "description",
            "preparation_time",
            "preperation_time_unit",
            "servings",
            "servings_unit",
            "preparation_step",
            "cover",
        )
        widgets = {
            "servings_unit": forms.Select(
                choices=(
                    ("Porções", "Porções"),
                    ("Pedaços", "Pedaços"),
                    ("Fatias", "Fatias"),
                )
            ),
            "preperation_time_unit": forms.Select(
                choices=(
                    ("Minutos", "Minutos"),
                    ("Horas", "Horas"),
                )
            ),
        }

recipes/views.py
import os

from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.views.generic import ListView

from recipes.models import Recipe

from .utils.pagination import make_pagination

PER_PAGES = int(os.environ.get('PER_PAGE', 6))

class RecipesListViewBase(ListView):
    model = Recipe
    context_object_name = 'recipes'
    paginate_by = None
    ordering =  ['-id']
    template_name = 'recipes/pages/home.html'

    def get_queryset(self, *args,**kwargs):
        query_set = super().get_queryset(*args,**kwargs)
        query_set = query_set.filter(
            is_published=True,
        )
        return query_set

    def get_context_data(self, *args,**kwargs):
        context = super().get_context_data(*args,**kwargs)

        page_object, pagination_range = make_pagination(
            self.request,
            context.get('recipes'),
            PER_PAGES
        )

        context.update(
            {
                'recipes': page_object,
                'pagination_range': pagination_range
            }
        )

        return context


class RecipesListViewHome(RecipesListViewBase):
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        title = 'Home | Recipes'

        context.update(
            {
                'title': title
            }
        )
        return context

class RecipesListCategory(RecipesListViewBase):
    template_name = 'recipes/pages/category.html'

    def get_queryset(self, *args,**kwargs):
        query_set = super().get_queryset(*args,**kwargs)

        query_set.filter(
            category__id=self.kwargs.get('category_id')
        )

        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        recipes = get_list_or_404(Recipe.objects.filter(
            category__id=self.kwargs.get('category_id')
        ).order_by('-id'))
        title = f"{recipes[0].category.name} - Category | Recipes"
        page_object, pagination_range = make_pagination(
        self.request, recipes, PER_PAGES)

        context.update(
            {
                'title': title,
                'recipes': page_object,
                'pagination_range': pagination_range
            }
        )
        return context

class RecipesListSearch(RecipesListViewBase):
    template_name = 'recipes/pages/search_page.html'

    def get_queryset(self, *args,**kwargs):
        query_set = super().get_queryset(*args,**kwargs)
        search_term = self.request.GET.get('q', '').strip()
        print('----------tá funcionando?--------')

        if not search_term:
            raise Http404()

        query_set.filter(
            Q(
                Q(title__icontains=search_term) |
                Q(description__icontains=search_term)
            ), is_published=True,
        ).order_by('-id')

        print(query_set)

        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '').strip()
        title = f'Search for "{search_term}" | Recipes'

        context.update(
            {
                'title': title,
                'search_term': search_term,
            }
        )
        return context








#These methods below are no longer being used. We refactored the home method using CBV,
# but this code snippet is still here for teaching purposes only
def home(request):
    title = 'Home | Recipes'
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')

    page_object, pagination_range = make_pagination(
        request, recipes, PER_PAGES)

    return render(
        request,
        'recipes/pages/home.html',
        context={'title': title, 'recipes': page_object,
                 'pagination_range': pagination_range}
    )


def recipe(request, recipe_id):
    recipe = get_object_or_404(Recipe, pk=recipe_id, is_published=True)
    title = f"{recipe.title} | Recipes'"
    return render(
        request,
        'recipes/pages/recipe_detail.html',
        context={'title': title, 'recipe': recipe, 'is_detail_page': True}
    )


def category(request, category_id):
    recipes = get_list_or_404(Recipe.objects.filter(
        category__id=category_id).order_by('-id'))
    title = f"{recipes[0].category.name} - Category | Recipes"

    page_object, pagination_range = make_pagination(
        request, recipes, PER_PAGES)

    return render(
        request,
        'recipes/pages/category.html',
        context={'title': title, 'recipes': page_object,
                 'pagination_range': pagination_range}
    )


def search(request):
    # strip tira espaços da string
    search_term = request.GET.get('q', '').strip()
    title = f'Search for "{search_term}" | Recipes'

    if not search_term:
        raise Http404()

    recipes = Recipe.objects.filter(
        Q(Q(title__icontains=search_term) | Q(
            description__icontains=search_term)), is_published=True,
    ).order_by('-id')

    return render(
        request,
        'recipes/pages/search_page.html',
        context={
            'title': title,
            'search_term': search_term,
            'recipes': recipes},
    )

recipes/views/api.py
from django.shortcuts import get_object_or_404
from rest_framework import status
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import ModelViewSet

from recipes.models import Recipe
from recipes.permissions import IsOwner
from recipes.serializers import RecipeSerializer

from ..permissions import IsOwner


class RecipeAPIv1Pagination(PageNumberPagination):
    page_size = 3


class RecipeAPIv1ViewSet(ModelViewSet):
    queryset = Recipe.objects.get_published()
    serializer_class = RecipeSerializer
    pagination_class = RecipeAPIv1Pagination
    permission_classes = [
        IsAuthenticatedOrReadOnly,
    ]
    http_method_names = ["get", "options", "head", "patch", "post", "delete"]

    def get_queryset(self):
        queryset = super().get_queryset()
        category_id = self.request.query_params.get("category_id", "")

        if category_id != "" and category_id.isnumeric():
            queryset = queryset.filter(category_id=category_id)

        return queryset

    def get_object(self):
        pk = self.kwargs.get("pk", "")
        obj = get_object_or_404(self.get_queryset(), pk=pk)

        self.check_object_permissions(self.request, obj)

        return obj

    def get_permissions(self):
        if self.request.method in ["PATCH", "DELETE"]:
            return [
                IsOwner(),
            ]

        return super().get_permissions()

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(author=request.user)
        headers = self.get_success_headers(serializer.data)

        return Response(
            serializer.data, status=status.HTTP_201_CREATED, headers=headers
        )

recipes/views/site.py
import os

from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.views.generic import ListView, DetailView

from recipes.models import Recipe

from ..utils.pagination import make_pagination

PER_PAGES = int(os.environ.get("PER_PAGE", 6))


class RecipesListViewBase(ListView):
    model = Recipe
    context_object_name = "recipes"
    paginate_by = None
    ordering = ["-id"]
    template_name = "recipes/pages/home.html"

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(
            is_published=True,
        )
        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        page_object, pagination_range = make_pagination(
            self.request, context.get("recipes"), PER_PAGES
        )

        context.update({"recipes": page_object, "pagination_range": pagination_range})

        return context


class RecipesListViewHome(RecipesListViewBase):
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        title = "Home | Recipes"

        context.update({"title": title})
        return context


class RecipeDetailView(DetailView):
    model = Recipe
    context_object_name = "recipe"
    template_name = "recipes/pages/recipe_detail.html"

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(is_published=True)
        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context.update({"is_detail_page": True})

        return context


class RecipesListCategory(RecipesListViewBase):
    template_name = "recipes/pages/category.html"

    def get_queryset(self, *args, **kwargs):
        query_set = super().get_queryset(*args, **kwargs)

        query_set.filter(category__id=self.kwargs.get("category_id"))

        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        recipes = get_list_or_404(
            Recipe.objects.filter(category__id=self.kwargs.get("category_id")).order_by(
                "-id"
            )
        )
        title = f"{recipes[0].category.name} - Category | Recipes"
        page_object, pagination_range = make_pagination(
            self.request, recipes, PER_PAGES
        )

        context.update(
            {
                "title": title,
                "recipes": page_object,
                "pagination_range": pagination_range,
            }
        )
        return context


class RecipesListSearch(RecipesListViewBase):
    template_name = "recipes/pages/search_page.html"

    def get_queryset(self, *args, **kwargs):
        search_term = self.request.GET.get("q", "").strip()
        if not search_term:
            raise Http404()

        query_set = super().get_queryset(*args, **kwargs)
        query_set = query_set.filter(
            Q(Q(title__icontains=search_term) | Q(description__icontains=search_term))
        ).order_by("-id")

        return query_set

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get("q", "").strip()
        title = f'Search for "{search_term}" | Recipes'

        context.update(
            {
                "title": title,
                "search_term": search_term,
            }
        )
        return context

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <div class="developer">
      <a href="linkedin.com/in/débora-gama/" target="_blank" rel="noreferrer noopener">By Débora Gama</a>
    </div>

    <div class="powered">
      <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
  </footer>

recipes/templates/recipes/partials/head.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/fontawesome.min.css" integrity="sha512-giQeaPns4lQTBMRpOOHsYnGw1tGVzbAIHUyHRgn7+6FmiEgGGjaG0T2LZJmAPMzRCl+Cug0ItQ2xDZpTmEc+CQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/brands.min.css" integrity="sha512-G/T7HQJXSeNV7mKMXeJKlYNJ0jrs8RsWzYG7rVACye+qrcUhEAYKYzaa+VFy6eFzM2+/JT1Q+eqBbZFSHmJQew==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/solid.min.css" integrity="sha512-6mc0R607di/biCutMUtU9K7NtNewiGQzrvWX4bWTeqmljZdJrwYvKJtnhgR+Ryvj+NRJ8+NnnCM/biGqMe/iRA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">


    <title>{{title}}</title>


</head>

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="{% url 'recipes:home'%}">
                <em class="fa-solid fa-utensils center"></em>
                <span class="main-logo-text"> Recipes </span>
            </a>
        </h1>
        {% include 'recipes/partials/login_button.html' %}
    </div>
</header>

recipes/templates/recipes/partials/login_button.html
<div class="user-login">
    {% if is_login_page is not True and is_dashboard_page is not True and is_dashboard_recipe is not True %}
    <a title="Área do usuário" href="{% url 'authors:login' %}">
        <em class="fa-solid fa-circle-user fa-2xl"></em>
    </a>
    {% endif %}
</div>

recipes/templates/recipes/partials/messages.html
{% if messages %}
<div class="main-content center container messages-container">
    {% for message in messages %}
    <div id="flash-message" class="message message-{{ message.tags }}">
        {{ message }}
    </div>
    <script>
        setTimeout(function () {
            let flashMessage = document.getElementById('flash-message');
            if (flashMessage) {
                flashMessage.style.display = 'none';
            }
        }, 2000);  // 2000 milliseconds (2 seconds)
    </script>
    {% endfor %}
</div>
{% endif %}

recipes/templates/recipes/partials/pagination.html
 {% if recipes.has_other_pages %}
    <div class="container pagination">
        <div class="pagination-content">
            {% if pagination_range.first_page_out_of_range %}
                <a class="page-link page-item" href="?page=1">1</a>
                <span class="page-item">...</span>
            {% endif %}

            {% for page in pagination_range.pagination %}
                <a class="page-link page-item" href="?page={{ page }}">{{ page }}</a>
            {% endfor %}

            {% if pagination_range.last_page_out_of_range %}
                <span class="page-item">...</span>
                <a class="page-link page-item" href="?page={{ pagination_range.total_pages }}">
                    {{ pagination_range.total_pages }}
                </a>
            {% endif %}
        <div/>
    </div>
{% endif %}

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{{ recipes.get_absolute_url }}">
            <img src="{{recipe.cover.url}}" alt="temp">
        </a>
    </div>

    <div class="recipe-title-container">
        <h2 class="recipe-title">
            {{ recipe.title }}
        </h2>
    </div>

    <div class="recipe-author">
        <span class="recipe-author-item">
            <em class="fa-regular fa-user"></em>
            {% if recipe.author.first_name %}
            {{recipe.author.first_name}} {{recipe.author.last_name}}
            {% else %}
            {{recipe.author.username}}
            {% endif %}
        </span>
        <span class="recipe-author-item">
            <em class="fa-solid fa-calendar-days"></em>
            {{recipe.created_at}}
        </span>

        {% if recipe.category is not None %}
        <span class="recipe-author-item">
            <a href="{% url 'recipes:category' recipe.category.id %}">
                <em class="fa-sharp fa-solid fa-layer-group"></em>
                <span>{{recipe.category.name}}</span>
            </a>
        </span>
        {% endif %}
    </div>

    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>

    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title">
                <em class="fa-solid fa-clock"></em>
                Preparo
            </h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title">
                <em class="fa-solid fa-pizza-slice"></em>
                Porções
            </h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit}}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
    <footer class="recipe-footer">
        <a href="{% url 'recipes:recipe' recipe.id %}" class="recipe-read-more button-dark button-full-width">
            <em class="fa-solid fa-eye"></em>
            <span>ver mais...</span>
        </a>
    </footer>
    {% else %}
    <div class="preparation-steps">
        {% if recipe.preparation_step_is_html is True %}
        {{recipe.preparation_step|safe}}
        {% else%}
        {{recipe.preparation_step|linebreaksbr}}
        {% endif %}
    </div>
    {% endif %}



</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">

        <form action="{% url 'recipes:search' %}" method="GET" class="search-form">
            <input type="search" class="search-input" name="q" value="{{search_term}}" required>
            <button type="submit" class="search-button"><em class="fa-sharp fa-solid fa-magnifying-glass"></em></button>
        </form>


    </div>

</div>