authors/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from . import views

app_name = "authors"
author_api_router = SimpleRouter()
author_api_router.register("api", views.AuthorViewSet, basename="author-api")

urlpatterns = [
    path("register/", views.register_view, name="register"),
    path("register/create/", views.register_create, name="register_create"),
    path("login/", views.login_view, name="login"),
    path("login/create/", views.login_create, name="login_create"),
    path("logout/", views.logout_view, name="logout"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path(
        "dashboard/recipe/create",
        views.DashboardRecipe.as_view(),
        name="dashboard_recipe_create",
    ),
    path(
        "dashboard/recipe/delete/",
        views.DashboardRecipeDelete.as_view(),
        name="dashboard_recipe_delete",
    ),
    path(
        "dashboard/recipe/<int:recipe_id>/edit/",
        views.DashboardRecipe.as_view(),
        name="dashboard_recipe_edit",
    ),
]

urlpatterns += author_api_router.urls

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipes.urls")),
    path("authors/", include("authors.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

authors/models.py
from django.db import models

# Create your models here.

authors/forms/login.py
from django import forms
from recipes.utils.django_forms import add_placeholder


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields["username"], "Type your username")
        add_placeholder(self.fields["password"], "Type your password")

    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

authors/forms/recipe_create_form.py
from django import forms
from collections import defaultdict
from recipes.models import Recipe
from recipes.utils.django_forms import add_attr
from recipes.utils.strings import is_positive_number
from django.core.exceptions import ValidationError
from authors.validators import AuthorCreateRecipeValidator


class AuthorCreateRecipeForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self._recipe_create_errors = defaultdict(list)

    class Meta:
        model = Recipe
        fields = (
            "title",
            "description",
            "preparation_time",
            "preperation_time_unit",
            "servings",
            "servings_unit",
            "category",
            "preparation_step",
            "cover",
        )
        widgets = {
            "servings_unit": forms.Select(
                choices=(
                    ("Porções", "Porções"),
                    ("Pedaços", "Pedaços"),
                    ("Fatias", "Fatias"),
                )
            ),
            "preperation_time_unit": forms.Select(
                choices=(
                    ("Minutos", "Minutos"),
                    ("Horas", "Horas"),
                )
            ),
        }

    def clean(self, *args, **kwargs):
        super_clean = super().clean(*args, **kwargs)
        AuthorCreateRecipeValidator(self.cleaned_data, error_class=ValidationError)
        return super_clean

authors/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from recipes.models import Recipe

from .forms import LoginForm, RegisterForm, AuthorRecipeForm, AuthorCreateRecipeForm

def register_view(request):
    """
    This view is responsible for rendering an empty form when in GET mode and
    receiving the register_form_data in the register redirection  create view.
    """
    title = 'Auhors | Register'
    register_form_data = request.session.get('register_form_data', None)
    form = RegisterForm(register_form_data)

    return render(
        request,
        'authors/pages/register_view.html',
        {
            'form': form,
            'title': title
        }
    )

def register_create(request):
    """
    This view will log the new user or throw an error if something is wrong.
    Redirect to register_view to disallow resubmit of the form.
    """
    if  not request.POST:
        raise Http404()

    POST = request.POST
    request.session['register_form_data'] = POST
    form = RegisterForm(POST)

    if form.is_valid():
        user = form.save(commit=False)
        #criptografando a senha antes de salvar na database
        user.set_password(user.password)
        user.save()
        messages.success(request, 'User successfully created. Please log in')

        del(request.session['register_form_data'])
        return redirect(reverse('authors:login'))

    return redirect('authors:register')


def login_view(request):
    title = 'Auhors | Login'
    form = LoginForm()
    return render(request, 'authors/pages/login.html', {
        'title': title,
        'form': form,
        'form_action': reverse('authors:login_create')
        }
    )


def login_create(request):
    """
    This view makes the authentication logic and redirect de user for login_view with
    appropriate messages of success or failed.
    """
    if not request.POST:
        raise Http404()

    form = LoginForm(request.POST)
    # login_url = reverse('authors:login')

    if form.is_valid():
        authenticated_user = authenticate(
            username=form.cleaned_data.get('username', ''),
            password=form.cleaned_data.get('password', ''),
        )
        if authenticated_user is not None:
            messages.success(request, 'Your are logged in')
            login(request, authenticated_user)
        else:
            messages.error(request, 'Invalid credentials')
    else:
        messages.error(request, 'Invalid username or password')

    return redirect(reverse('authors:dashboard'))

@login_required(login_url='authors:login', redirect_field_name='next')
def logout_view(request):
    """
    View wich contains the logout logical and messages. Redirect the user back for login view.
    """
    if not request.POST:
        return redirect(reverse('authors:login'))

    messages.success(request, 'Logged out successfully')
    logout(request)
    return redirect(reverse('authors:login'))


@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_view(request):
    """
    This view lists the author´s recipes.
    """
    title = 'Authors | Dashboard'
    recipes = Recipe.objects.filter(
        is_published=False,
        author = request.user,
    )

    return render(request, 'authors/pages/dashboard.html', {
      'title': title,
      'recipes': recipes,
      }
    )


@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_recipe_edit(request, recipe_id):
    """
    This view makes it possible to edit recipes
    """
    title = 'Authors | Dashboard Edit Recipe'
    recipe = Recipe.objects.filter(
        is_published=False,
        author = request.user,
        pk = recipe_id,
    ).first()

    if not recipe:
        raise Http404()

    form =AuthorRecipeForm(request.POST or None,files=request.FILES or None, instance=recipe)

    if form.is_valid():
        # salvando os dados na variável antes de salvar na base de dados
        recipe = form.save(commit=False)

        recipe.author = request.user
        recipe.preparation_step_is_html = False
        recipe.is_published = False

        # salvando na base de dados após verifcações feitas acima
        recipe.save()
        messages.success(request, 'Your recipe was saved!')
        return redirect(reverse('authors:dashboard_recipe_edit', args=(recipe_id,)))

    return render(request, 'authors/pages/dashboard_recipe.html', {
      'title': title,
      'recipe': recipe,
      'form': form,
      }
    )


@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_recipe_create(request):
    """
    This view makes it possible to create new recipes
    """
    title = 'Authors | Dashboard Create Recipe'
    recipe = Recipe()

    form =AuthorCreateRecipeForm(request.POST or None,files=request.FILES or None, instance=recipe)

    if form.is_valid():
        # salvando os dados na variável antes de salvar na base de dados
        recipe = form.save(commit=False)

        recipe.author = request.user
        recipe.preparation_step_is_html = False
        recipe.is_published = False

        # salvando na base de dados após verifcações feitas acima
        recipe.save()
        messages.success(request, 'Your recipe was created!')
        return redirect(reverse('authors:dashboard_recipe_edit', args=(recipe.id,)))
        # return redirect(reverse('authors:dashboard_recipe_create'))

    return render(request, 'authors/pages/dashboard_recipe_create.html', {
      'title': title,
    #   'recipe': recipe,
      'form': form,
      }
    )


@login_required(login_url='authors:login', redirect_field_name='next')
def dashboard_recipe_delete(request):
    """
    This view makes it possible to delete recipes
    """
    if  not request.POST:
        raise Http404()

    POST = request.POST
    recipe_id = POST.get('id')

    recipe = Recipe.objects.filter(
        is_published=False,
        author = request.user,
        pk = recipe_id,
    ).first()

    if not recipe:
        raise Http404()

    recipe.delete()
    messages.success(request, 'Deleted successfully')
    return redirect('authors:dashboard')

authors/views/all.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse

from authors.forms import (
    AuthorCreateRecipeForm,
    AuthorRecipeForm,
    LoginForm,
    RegisterForm,
)
from recipes.models import Recipe


def register_view(request):
    """
    This view is responsible for rendering an empty form when in GET mode and
    receiving the register_form_data in the register redirection  create view.
    """
    title = "Authors | Register"
    register_form_data = request.session.get("register_form_data", None)
    form = RegisterForm(register_form_data)

    return render(
        request, "authors/pages/register_view.html", {"form": form, "title": title}
    )


def register_create(request):
    """
    This view will log the new user or throw an error if something is wrong.
    Redirect to register_view to disallow resubmit of the form.
    """
    if not request.POST:
        raise Http404()

    POST = request.POST
    request.session["register_form_data"] = POST
    form = RegisterForm(POST)

    if form.is_valid():
        user = form.save(commit=False)
        # encrypting the password before saving to the database
        user.set_password(user.password)
        user.save()
        messages.success(request, "User successfully created. Please log in")

        del request.session["register_form_data"]
        return redirect(reverse("authors:login"))

    return redirect("authors:register")


def login_view(request):
    title = "Authors | Login"
    form = LoginForm()
    return render(
        request,
        "authors/pages/login.html",
        {
            "title": title,
            "form": form,
            "is_login_page": True,
            "form_action": reverse("authors:login_create"),
        },
    )


def login_create(request):
    """
    This view makes the authentication logic and redirect de user for login_view with
    appropriate messages of success or failed.
    """
    if not request.POST:
        raise Http404()

    form = LoginForm(request.POST)

    if form.is_valid():
        authenticated_user = authenticate(
            username=form.cleaned_data.get("username", ""),
            password=form.cleaned_data.get("password", ""),
        )
        if authenticated_user is not None:
            messages.success(request, "You are logged in")
            login(request, authenticated_user)
        else:
            messages.error(request, "Invalid credentials")
    else:
        messages.error(request, "Invalid username or password")

    return redirect(reverse("authors:dashboard"))


@login_required(login_url="authors:login", redirect_field_name="next")
def logout_view(request):
    """
    View wich contains the logout logical and messages. Redirect the user back for login view.
    """
    if not request.POST:
        return redirect(reverse("authors:login"))

    messages.success(request, "Logged out successfully")
    logout(request)
    return redirect(reverse("authors:login"))


@login_required(login_url="authors:login", redirect_field_name="next")
def dashboard_view(request):
    """
    This view lists the author´s recipes.
    """
    title = "Authors | Dashboard"
    recipes = Recipe.objects.filter(
        author=request.user,
    ).order_by("is_published")

    return render(
        request,
        "authors/pages/dashboard.html",
        {
            "title": title,
            "recipes": recipes,
            "is_dashboard_page": True,
        },
    )

authors/views/api.py
from django.contrib.auth import get_user_model
from rest_framework.permissions import IsAuthenticated
from rest_framework.serializers import ModelSerializer
from rest_framework.viewsets import ReadOnlyModelViewSet

from ..serializers import AuthorSerializer


class AuthorViewSet(ReadOnlyModelViewSet):
    serializer_class = AuthorSerializer
    permission_classes = [
        IsAuthenticated,
    ]
    http_method_names = ["get"]

    def get_queryset(self):
        user = get_user_model()
        queryset = user.objects.filter(username=self.request.user.username)

        return queryset

authors/views/dashboard_recipe.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from authors.forms import AuthorRecipeForm, AuthorCreateRecipeForm
from recipes.models import Recipe


# decorating dispatch method of generic View
@method_decorator(
    login_required(login_url="authors:login", redirect_field_name=next), name="dispatch"
)
class DashboardRecipe(View):
    def render_recipe(self, form, title, recipe, is_dashboard):
        return render(
            self.request,
            "authors/pages/dashboard_recipe.html",
            context={
                "title": title,
                "recipe": recipe,
                "form": form,
                "is_dashboard_page": is_dashboard,
            },
        )

    def get_recipe(self, recipe_id=None):
        recipe = None

        if recipe_id is not None:
            recipe = Recipe.objects.filter(
                is_published=False,
                author=self.request.user,
                pk=recipe_id,
            ).first()

            if not recipe:
                raise Http404()

        return recipe

    def get(self, request, recipe_id=None):
        recipe = self.get_recipe(recipe_id)
        title = "Authors | Dashboard Edit Recipe"
        form = AuthorRecipeForm(instance=recipe)
        is_dashboard = True

        return self.render_recipe(form, title, recipe, is_dashboard)

    def post(self, request, recipe_id=None):
        recipe = self.get_recipe(recipe_id)
        title = "Authors | Dashboard Edit Recipe"
        form = AuthorCreateRecipeForm(
            data=request.POST or None, files=request.FILES or None, instance=recipe
        )
        is_dashboard = True

        if form.is_valid():
            # salvando os dados na variável antes de salvar na base de dados
            recipe = form.save(commit=False)

            recipe.author = request.user
            recipe.preparation_step_is_html = False
            recipe.is_published = False

            # salvando na base de dados após verifcações feitas acima
            recipe.save()
            messages.success(request, "Your recipe was saved!")
            return redirect(reverse("authors:dashboard_recipe_edit", args=(recipe.id,)))

        return self.render_recipe(form, title, recipe, is_dashboard)


@method_decorator(
    login_required(login_url="authors:login", redirect_field_name=next), name="dispatch"
)
class DashboardRecipeDelete(DashboardRecipe):
    def post(self, *args, **kwargs):
        recipe = self.get_recipe(self.request.POST.get("id"))
        recipe.delete()

        messages.success(self.request, "Deleted successfully")
        return redirect("authors:dashboard")

authors/templates/authors/pages/dashboard.html
{% load static %}
{% include 'recipes/partials/head.html' %}

{% block content %}
{% include 'recipes/partials/header.html' %}
{% include 'recipes/partials/messages.html' %}

<div class=" main-content center container">
    {% include 'authors/partials/dashboard_menu.html' %}
    {% include 'recipes/partials/search.html' %}

    <div class="author-dashboard-container">
        <div class="author-dashboard-recipes-list">
            <ul>
                {% for recipe in recipes %}
                <li>
                    <span class="recipe-li-item-title">
                        {{recipe.title}}
                    </span>
                    <span class="recipe-li-item">
                        {% if recipe.is_published%}
                        <span class="published_recipe" title="Publicada">
                            <em class="fa-solid fa-check fa-lg"></em>
                        </span>
                        {% else %}
                        <span class="not_published_recipe" title="Aguardando publicação">
                            <em class="fa-solid fa-circle-exclamation fa-lg"></em>
                        </span>
                        {% endif %}
                    </span>
                    {% if not recipe.is_published %}
                    <span class="recipe-li-item" title="Deletar">
                        <form class="form-delete" action="{% url 'authors:dashboard_recipe_delete' %}" method='POST'>
                            {% csrf_token %}
                            <input type="hidden" name="id" value={{recipe.id}}>
                            <button type="submit"><em class="fa-solid fa-trash fa-lg"></em></button>
                        </form>
                        {% else %}
                        <span class="recipe-li-item"></span>
                        {% endif %}
                    </span>
                    {% if not recipe.is_published %}
                    <span class="recipe-li-item" title="Editar">
                        <form class="form-edit" action="{% url 'authors:dashboard_recipe_edit' recipe.id %}"
                            method='GET'>
                            {% csrf_token %}
                            <input type="hidden" name="id" value={{recipe.id}}>
                            <button type="submit"> <em class="fa-solid fa-pen-to-square fa-lg"></em></button>
                        </form>
                        {% else %}
                        <span class="recipe-li-item"></span>
                        {% endif %}
                    </span>
                </li>
                {% empty %}
                <li>
                    <p> You do not have non published recipes... please create one.</p>
                </li>
                {% endfor %}
            </ul>
        </div>

    </div>
</div>
{% include 'recipes/partials/footer.html' %}
<script src="{% static 'recipes/js/scripts.js' %}"></script>
{% endblock content %}

authors/templates/authors/pages/dashboard_recipe.html
{% include 'recipes/partials/head.html' %}

{% block content %}
{% include 'recipes/partials/header.html' %}

<div class="main-content center container">
    {% include 'recipes/partials/messages.html' %}
    {% include 'authors/partials/dashboard_menu.html' %}

    <form method="POST" enctype='multipart/form-data'>
        {% csrf_token %}

        <div class="form-content recipe-form">
            {% for field in form %}
            <div class="form-group {{field.field.widget.attrs.class}}">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{field}}

                {% if field.help_text %}
                <p class="help-text">{{ field.help_text }}</p>
                {% endif %}

                {{ field.errors }}
            </div>

            {% if field.name == 'cover' and field.value.url %}
            <div>
                <img src="{{field.value.url}}" alt="Cover for {{recipe.title}}">
            </div>
            {% endif %}
            {% endfor %}
        </div>

        {% if form.errors %}
        <div class="main-content center container messages-container">
            <div class="message message-error">
                There are errors in the form. Please fix them, and send again
            </div>
        </div>
        {% endif %}
        <div class="form-group">
            <button type="submit">Send</button>

    </form>
</div>

</div>
{% include 'recipes/partials/footer.html' %}

{% endblock content %}

authors/templates/authors/pages/login.html
{% include 'recipes/partials/head.html' %}

{% block content %}
{% include 'recipes/partials/header.html' %}
<div class=" main-content center container">
    {% include 'authors/partials/dashboard_menu.html' %}
</div>
{% include 'recipes/partials/messages.html' %}


<div class=" main-content center container">
    {% if not request.user.is_authenticated %}
    <h1>Login</h1>
    <p>Ainda não tem cadastro? Registre-se <a href="{% url 'authors:register' %}">aqui</a>.</p>

    <form class="form-login" action="{% url 'authors:login_create' %}" method="POST">
        {% csrf_token %}

        <div class="form-content form-content-grid">
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{field}}

                {% if field.help_text %}
                <p class="help-text">{{ field.help_text }}</p>
                {% endif %}

                {{ field.errors }}
            </div>
            {% endfor %}
        </div>

        {% if form.errors %}
        <div class="main-content center container messages-container">
            <div class="message message-error">
                There are errors in the form. Please fix them, and send again
            </div>
        </div>

        {% endif %}

        <div class="form-group center">
            <button type="submit">Login</button>
        </div>
    </form>
    {% endif %}

</div>
{% include 'recipes/partials/footer.html' %}
{% endblock content %}

authors/templates/authors/pages/register_view.html
{% include 'recipes/partials/head.html' %}

{% block content %}
{% include 'recipes/partials/header.html' %}


<div class="main-content center container">
    <h1>Register</h1>
</div>

{% include 'recipes/partials/messages.html' %}

<div class="main-content register-form container">
    <form action="{% url 'authors:register_create' %}" method="POST">
        {% csrf_token %}

        <div class="form-content form-content-grid">
            {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{field}}

                {% if field.help_text %}
                <p class="help-text">{{ field.help_text }}</p>
                {% endif %}

                {{ field.errors }}
            </div>
            {% endfor %}
        </div>

        {% if form.errors %}
        <div class="main-content center container messages-container">
            <div class="message message-error">
                There are errors in the form. Please fix them, and send again
            </div>
        </div>
        {% endif %}

        <div class="form-group">
            <button type="submit">Send</button>
        </div>
    </form>
</div>
{% include 'recipes/partials/footer.html' %}
{% endblock content %}